### ISSUE TITLE
Размер текста на карточках животных

### ISSUE THREAD

**Issue by FoxVol** [ingbrzy/MA-XML-13-RUSSIAN#11]
13.0.5.0, Poco F3 (alioth)
Обнаружил косяки с размером шрифта на трёх карточках с описанием животных в настройках звука уведомлений, а также отсутствие в переводе буквы "ё", не чЕрный, а чЁрный, не тЕмная тема, а тЁмная тема (если это невозможно решить, тогда ладно).
![Screenshot_2022-06-07-14-35-26-615_com xiaomi misettings](https://user-images.githubusercontent.com/106919460/172381310-b9725d98-ad7f-4ea8-94e3-5318d97a3040.png)
![Screenshot_2022-06-07-14-35-49-696_com xiaomi misettings](https://user-images.githubusercontent.com/106919460/172381329-59363941-11b2-411b-bb38-167d9cd8b5d9.png)
![Screenshot_2022-06-07-14-36-14-474_com xiaomi misettings](https://user-images.githubusercontent.com/106919460/172381341-030538fc-194d-4f08-a352-c714680fea26.png)
![IMG_20220607_144415](https://user-images.githubusercontent.com/106919460/172381866-cb26c2d8-5633-4262-87de-c7b0ba654376.jpg)
Простите за беспокойство, если это уже исправлено в еженедельных сборках.

**Comment by mclaude74** [comment]
@FoxVol 
Изменение размера шрифта мне недоступно, к сожалению.
К тому же, на русском научные названия слишком длинные (специально гуглил названия), сократить их не получится.

Оптимизировал описания животных так, чтобы с бОльшей вероятностью отображались полностью.
Будет ли описание влезать полностью - еще зависит от стиля шрифта и DPI в Настройках разработчика.

Темный, черный  - заменил на тёмный, чёрный.

По возможности, предложения и замечания пишите в теме по ссылке: https://github.com/ingbrzy/MA-XML-13-RUSSIAN/issues/1

**Comment by ministr91** [comment]
@mclaude74 @FoxVol это не ошибка, что вместо "ё" стоит "е". Допускается оба варианта
