### ISSUE TITLE
Ошибка в слове, в настройках наушников Redmi Buds 3 pro

### ISSUE THREAD

**Issue by NatieLassi** [ingbrzy/MA-XML-13-RUSSIAN#14]
![upload_2022_09_30_14_39_57_714](https://user-images.githubusercontent.com/108834326/193242051-9fdab073-3637-4e5a-85c5-6d93d07d7542.jpg)

**Comment by mclaude74** [comment]
@NatieLassi 
какое именно приложение и какая прошивка?

Проверил репозиторий перевода, такой опечатки нет.
Либо это стороннее приложение, не входящее в состав прошивки xiaomi.eu, либо это прошивка не от xiaomi.eu
