### ISSUE TITLE
Нет перевода [Sweet]

### ISSUE THREAD

**Issue by s1upy** [ingbrzy/MA-XML-13-RUSSIAN#16]
Xiaomi.EU 13.0.16.0
![IMG_20230207_204111](https://user-images.githubusercontent.com/64200055/217325437-a6979a86-97f4-471d-9422-35e31a803f15.jpg)

**Comment by mclaude74** [comment]
@Slupy 
Для MIUI13 в исходном репозитории для еженедельных нет такой строки. Перевод для стабильных берется из репозитория для еженедельных.

В репозитории для  MIUI14 (https://github.com/ingbrzy/MA-XML-14-RUSSIAN/issues/1) есть такая строка и есть перевод:

`<string name="delete_media_for_cloud">Selected items will be removed from the cloud and all synced devices to Recently deleted items.</string>`

`<string name="delete_media_for_cloud">Выбранные файлы будут удалены из облака и на всех подключённых устройствах и сохранены в Корзине</string>`

Я перекину недостающие строки из репозитория перевода для MIUI14 в репозиторий для MIUI13.
Но по факту поддержка перевода для MIUI13 завершена, т.к. новые изменения в ресурсах не публикуются.

**Comment by s1upy** [comment]
@mclaude74 Спасибо!
