### ISSUE TITLE
Network and Miui+ Translation

### ISSUE THREAD

**Issue by Andrex22876** [ingbrzy/MA-XML-13-RUSSIAN#5]
Device: Mi 11 Lite 5G (renoir) MIUI 13.
Network and Miui+ bad translate!
Screenshots: 
![Screenshot_2022-02-04-09-59-16-347_com android settings](https://user-images.githubusercontent.com/98189279/152500963-394616bd-ed18-4bec-be8f-db205dd89711.jpg)
![Screenshot_2022-02-04-09-59-23-169_com android settings](https://user-images.githubusercontent.com/98189279/152500998-f21bc67e-c083-4b2e-931d-2ec4f158f18a.jpg)
![Screenshot_2022-02-04-09-59-39-193_com android chrome](https://user-images.githubusercontent.com/98189279/152501023-80b18bd2-01b5-43e3-8053-dfb7bbda594f.jpg)
![Screenshot_2022-02-04-10-02-11-054_com xiaomi mirror](https://user-images.githubusercontent.com/98189279/152501309-6bfe1a43-1f0c-4400-8aa1-e6c17856cca5.jpg)
![Screenshot_2022-02-04-10-02-12-894_com xiaomi mirror](https://user-images.githubusercontent.com/98189279/152501355-2a658c4b-e6b2-4d87-a00e-7b94b9788193.jpg)
![Screenshot_2022-02-04-10-02-15-982_com xiaomi mirror](https://user-images.githubusercontent.com/98189279/152501382-397ad410-0090-40bc-9e30-c079d4a085ef.jpg)

**Comment by mclaude74** [comment]
@Andrex22876 
Добавлен массив [wifitrackerlib_wifi_status](https://github.com/ingbrzy/MA-XML-13-RUSSIAN/commit/2c0cd017ee9c209c9ef759deb25210e84de6b60f) в Настройки - возможно, дело было в его отсутствии. Во всех других ресурсах он присутствует.
Добавлен доперевод для Mirror.apk (MIUI+).

О недопереводе лучше сообщать в [этой теме](https://github.com/ingbrzy/MA-XML-13-RUSSIAN/issues/1). Во втором посте, по возможности, публикую актуальную информацию.

**Comment by Andrex22876** [comment]
> @Andrex22876 Добавлен массив [wifitrackerlib_wifi_status](https://github.com/ingbrzy/MA-XML-13-RUSSIAN/commit/2c0cd017ee9c209c9ef759deb25210e84de6b60f) в Настройки - возможно, дело было в его отсутствии. Во всех других ресурсах он присутствует. Добавлен доперевод для Mirror.apk (MIUI+).
> 
> О недопереводе лучше сообщать в [этой теме](https://github.com/ingbrzy/MA-XML-13-RUSSIAN/issues/1). Во втором посте, по возможности, публикую актуальную информацию.

Спасибо можна сам файл settings.apk уже с переводом?

**Comment by mclaude74** [comment]
@Andrex22876 
Я только добавляю перевод в репозиторий (общее положение дел описано в ссылке на тему в предыдущем посте).
Вкратце - сборкой не занимаюсь, тем более нет инструментов для корректной сборки, у xiaomi.eu свои инструменты, которыми они не делятся. Надо ждать, когда они выпустят следующую сборку с обновленным переводом.
