### ISSUE TITLE
Fix translate

### ISSUE THREAD

**Issue by Andrex22876** [ingbrzy/MA-XML-13-RUSSIAN#6]
Можно пожалуйста пофиксить в центре управление надпись: "Геолокация" → "Местоположение" и "Запрет автоповорота" → "Блокировка ориентации" как и в оригинале.
![IMG_20220213_190319](https://user-images.githubusercontent.com/98189279/153768355-0672cf4d-908a-448c-b6c9-2d576fbdf8e4.jpg)
![IMG_20220213_190346](https://user-images.githubusercontent.com/98189279/153768363-ee5aad4e-6227-4836-ba8d-8467e0b7aa4b.jpg)
![IMG_20220213_190436](https://user-images.githubusercontent.com/98189279/153768369-c391d81a-a046-4504-bf72-5d76c8d06261.jpg)

**Comment by mclaude74** [comment]
@Andrex22876 
Какая прошивка и устройство?

В моем случае (xiaomi.eu 22.2.9) Геолокация ведет на Геолокацию.

![image](https://user-images.githubusercontent.com/45774262/153775857-aa64a547-e182-463e-ab14-76174c6bf9e9.png)

Насчет "Блокировка ориентации" - в шторке уже имеется тоггл "Блокировка". 
Чем "Блокировка ориентации" лучше "Запрета автоповорота", который более точно описывает действие тоггла? Мы же не блокируем ориентацию в альбомном режиме?

**Comment by Andrex22876** [comment]
> @Andrex22876 Какая прошивка и устройство?
> 
> В моем случае (xiaomi.eu 22.2.9) Геолокация ведет на Геолокацию.
> 
> ![image](https://user-images.githubusercontent.com/45774262/153775857-aa64a547-e182-463e-ab14-76174c6bf9e9.png)
> 
> Насчет "Блокировка ориентации" - в шторке уже имеется тоггл "Блокировка". Чем "Блокировка ориентации" лучше "Запрета автоповорота", который более точно описывает действие тоггла? Мы же не блокируем ориентацию в альбомном режиме?

На счёт Запрет автоповорота соглашусь, но с Геолокацией нужно поменять либо в настройках Местоположение → Геолокация либо на оборот.

**Comment by Andrex22876** [comment]
> @Andrex22876 Ниже скрины с моего устройства (еженедельная 22.2.9), как видно на них все приведено к одному "знаменателю" Геолокация. У вас по другому?
> 
> Геолокация, на мой взгляд, более удачный вариант, т.к. короче, ближе к обозначению действия, расшифровывается как "определение местоположения". В ресурсах чистого A12 также используются понятия геолокация и геоданные.
> 
> ![image](https://user-images.githubusercontent.com/45774262/154071745-b770ea01-3e48-44ae-8e15-e83abbe9959e.png) ![image](https://user-images.githubusercontent.com/45774262/154071784-50eaff23-75e1-4d77-bb26-e7873e17dff2.png) ![image](https://user-images.githubusercontent.com/45774262/154071821-a8c2408a-4701-40fa-aa37-972339b85832.png) ![image](https://user-images.githubusercontent.com/45774262/154071868-22f511f0-b700-4911-b914-73ec5b52d39b.png) ![image](https://user-images.githubusercontent.com/45774262/154071984-80e706b3-815a-4104-9ca4-74476c93ab8d.png) ![image](https://user-images.githubusercontent.com/45774262/154072017-e680d0b4-23a1-4627-9a43-19a312b6616f.png) ![image](https://user-images.githubusercontent.com/45774262/154072059-40c49c90-4a9c-48ba-a4cc-b3ff4e931a01.png) ![image](https://user-images.githubusercontent.com/45774262/154072096-28d21feb-f1b9-4fa9-9ed2-3ede98a54e26.png) ![image](https://user-images.githubusercontent.com/45774262/154072131-28e2c898-41bf-4f8c-a709-50608e9ce792.png)

Пусть будет геолокация но нужно это исправить везде 
![Screenshot_2022-02-15-14-37-58-225_com android settings](https://user-images.githubusercontent.com/98189279/154073145-35fb5450-3058-4720-88e8-88f5a6a383ae.jpg)

**Comment by mclaude74** [comment]
@Andrex22876 

На вашем устройстве (renoir) установлена `22.2.9 еженедельная`? 
Актуальный перевод начинается именно с этой версии.

Если же стоит `стабильная` xiaomi.eu_multi_MI11Lite5G_V13.0.4.0.SKICNXM_v13-12-fastboot.zip от 2022-01-06, то там правильный перевод появится позже (не знаю когда, т.к. график выхода мне неизвестен, и по каким-то причинам не всегда при сборке используется актуальный перевод). Стабильные сборки вне возможности контроля с моей стороны.

Если же стоит последняя еженедельная, можно попробовать очистить данные приложения Настройки или содержимое папки /data/system/package_cache 
"Измененный" перевод бывает также в случае использования сторонней темы или каких-либо патчей.

**Comment by Andrex22876** [comment]
> 

13.0.7.0 Stable

**Comment by Andrex22876** [comment]
> @Andrex22876
> 
> На вашем устройстве (renoir) установлена `22.2.9 еженедельная`? Актуальный перевод начинается именно с этой версии.
> 
> Если же стоит `стабильная` xiaomi.eu_multi_MI11Lite5G_V13.0.4.0.SKICNXM_v13-12-fastboot.zip от 2022-01-06, то там правильный перевод появится позже (не знаю когда, т.к. график выхода мне неизвестен, и по каким-то причинам не всегда при сборке используется актуальный перевод). Стабильные сборки вне возможности контроля с моей стороны.
> 
> Если же стоит последняя еженедельная, можно попробовать очистить данные приложения Настройки или содержимое папки /data/system/package_cache "Измененный" перевод бывает также в случае использования сторонней темы или каких-либо патчей.

![Screenshot_2022-02-15-15-15-13-420_com android settings](https://user-images.githubusercontent.com/98189279/154079553-8f1101a4-776f-488d-ab9e-c48be67ea258.jpg)

**Comment by mclaude74** [comment]
@Andrex22876 
Теперь понятно. 
В прошлом посте я написал причину неактуальности перевода.
Перевод был актуализирован именно 22.2.9

xiaomi.eu выкладывает изменения в ресурсах только для еженедельных прошивок, соответственно перевод заточен на них. 
В стабильные перевод попадает позже, из еженедельных. В некоторых случаях бывают более длительные задержки, если в сборке приложение не обновляется.

**Comment by Andrex22876** [comment]
> @Andrex22876 Теперь понятно. В прошлом посте я написал причину неактуальности перевода. Перевод был актуализирован именно 22.2.9
> 
> xiaomi.eu выкладывает изменения в ресурсах только для еженедельных прошивок, соответственно перевод заточен на них. В стабильные перевод попадает позже, из еженедельных. В некоторых случаях бывают более длительные задержки, если в сборке приложение не обновляется.

Спасибо за информацию!
